# myName = input("What's you name?: ")
# myAge = input("How old are you? :")
# print("Gee, that's REALLY OLD")
# replit = input("Do you like Replit?")
# print("OF COURSE YOU DO!")
# print()
# print("So, you are")
# print(myName)
# print("and are the ripe old age of")
# print(myAge)
# print("and clearly think that Replit is")
# print(replit)

# Fixing My Code

# my_variable = input("WHO GOES THERE? ")
# print(my_variable)

# myGrandma = input("How's your Grandma doing? 😘 ")
# print(myGrandma)

# myLunch = input("What are you having for lunch? ")
# print("Hmm, it sounds like you really should just order")
# print(myLunch)
# print("as soon as possible!")

# Challenge part 1
# print("Definitely not a Phishing Scam")
# print()
# myName = input("Your Name")
# print("Thanks for logging in")
# print(myName)
# cardNumber = input("What is your credit card number?")
# print("Thanks, I definitely wont put")
# print(cardNumber)
# print("into Amazon and order anything weird")
# print()
# print("Promise")
# maidenName = input("What is your Mother's maiden name? ")
# print()
# print("That's cool, I just wanted to know that")
# print(maidenName)
# print("was your Mum's maiden name. Not because the bank requested it or anything, honest.")

print("Getting to Know You")
print()
name = input("Name : ")
print()
age = input("Age : ")
print()
food = input("Fav Food : ")
print()
music = input("Fav Music: ")
print()
city = ("City : ")
print()
print()
print("Your name is " + name)
print("You are " + age + "yrs old")
print("Fav Food is " + food)
print("Fav Music " + music)
print("You live in ")
print(city)
 
